version: '3'

services:

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306
      - 33060:33060

  stock-manager:
    image: lucasvilela/stock-manager
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=bootdb
      - DATABASE_PORT=3306

  stock-quote-manager:
    image: lucasvilela/stock-quote-manager
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - 8081:8081
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=bootdb
      - DATABASE_PORT=3306
