version: '3'


networks:
  
  backend:
  
services:

  db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bootdb
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
    ports:
      - 3306:3306
      - 33060:33060
    networks:
      - backend

  stock-manager:
    image: fabianocruz123/stock-manager-image:v1
    #restart: on-failure
    depends_on:
      - db
    ports:
      - 8080:8080
    environment:
      - DATABASE_HOST=db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=bootdb
      - DATABASE_PORT=3306
    networks:
      - backend     

  stock-quote-manager:
    image: fabianocruz123/stock-quote-image:v1
    #restart: on-failure
    depends_on:
      - db
    ports:
      - 8081:8081
    environment:
      - DATABASE_HOST=db 
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_NAME=bootdb
      - DATABASE_PORT=3306
    networks:
      - backend     
    
    